#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

puts "Compiling..."
filename = ARGV[0]
run = "java -cp bin:lib/antlr-4.4-complete.jar wacc/Main #{filename}"
exec run
